import './globals.css';
import { Inter } from 'next/font/google';
import {
	ClerkProvider,
	RedirectToSignIn,
	SignIn,
	SignedIn,
	SignedOut,
} from '@clerk/nextjs';
import { ThemeProvider } from '@/context/ThemeProvider';
import SideBar from '@/components/view/SideBar';
import { redirect } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<SignedIn>
						<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
							<main className="lg:flex max-w-[100vw] max-h-screen bg-background">
								<SideBar />
								{children}
							</main>
						</ThemeProvider>
					</SignedIn>
					<SignedOut>
						{
							<>
								<RedirectToSignIn /> <SignIn />
							</>
						}
					</SignedOut>
				</body>
			</html>
		</ClerkProvider>
	);
}
