import './globals.css';
import { Inter } from 'next/font/google';
import { ClerkProvider, currentUser } from '@clerk/nextjs';
import { ThemeProvider } from '@/context/ThemeProvider';
import SideBar from '@/components/view/SideBar';
import { CastedUser } from './dashboard/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const user = await currentUser();

	const castedUser: CastedUser = {
		id: user?.id!,
		firstName: user?.firstName!,
		lastName: user?.lastName!,
		emailAddress: user?.emailAddresses[0].emailAddress!,
		imageUrl: user?.imageUrl!,
	};

	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
						<main className="lg:flex max-w-[100vw] max-h-screen bg-background">
							<SideBar currentUser={castedUser} />
							{children}
						</main>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
